project:
  type: website
  output-dir: docs

website:
  title: "Nicholas Varabioff's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nvarabioff
      - icon: twitter
        href: https://x.com/nickvarabioff
format:
  html:
    theme: cosmo
    css: styles.css



